CXX = clang++
CXXFLAGS += -std=c++11

DSTS = Box BrokenBox SafeBox BoxLambda BoxCondVar BoxTest

all: $(DSTS)

clean:
	rm $(DSTS)

Box:		Box.cpp
BrokenBox:	BrokenBox.cpp
SafeBox:	SafeBox.cpp
BoxLambda:	BoxLambda.cpp
BoxCondVar:	BoxCondVar.cpp
BoxTest:	BoxTest.cpp
