CXX = clang++ -std=c++11
#CXXFLAGS =

DSTS = ThreadExample1 ThreadExample2 ThreadExample3 Terminate

all: $(DSTS)

clean:
	rm $(DSTS)

ThreadExample1: ThreadExample1.cpp
ThreadExample2: ThreadExample2.cpp
ThreadExample3: ThreadExample3.cpp
Terminate:	Terminate.cpp
